--  Generate SQL 
--  Version:                   	V7R2M0 140418 
--  Generated on:              	23/05/17 13:20:29 
--  Relational Database:       	TALENTIT 
--  Standards Option:          	DB2 for i 
CREATE PROCEDURE WORKSHOP/CREATEINVOICEDETAIL ( 
	IN "ID" CHAR(15) , 
	IN DETLINE SMALLINT , 
	IN PRODID CHAR(15) , 
	IN INVQTY DECIMAL(7, 2) , 
	IN MEASUR CHAR(5) , 
	IN PRICE DECIMAL(9, 2) , 
	IN INVVAT CHAR(5) , 
	IN INVTXT VARCHAR(256) , 
	OUT SUCCESS SMALLINT ) 
	DYNAMIC RESULT SETS 1 
	LANGUAGE RPGLE 
	SPECIFIC WORKSHOP/CRTONEINVOICE 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	EXTERNAL NAME 'WORKSHOP/IOINVDETL(CRTONEINVOICE)' 
	PARAMETER STYLE SQL ; 
  
GRANT ALTER , EXECUTE   
ON SPECIFIC PROCEDURE WORKSHOP/CRTONEINVOICE 
TO JENTE ;
