--  Generate SQL 
--  Version:                   	V7R2M0 140418 
--  Generated on:              	23/05/17 13:20:56 
--  Relational Database:       	TALENTIT 
--  Standards Option:          	DB2 for i 
CREATE PROCEDURE WORKSHOP/CREATEINVOICEHEADER ( 
	IN CUSID CHAR(15) , 
	IN ADDID CHAR(15) , 
	IN ADDDLV CHAR(15) , 
	IN INVDATE DATE , 
	IN INVDDATE DATE , 
	IN INVSTATUS CHAR(5) , 
	IN INVTYPE CHAR(5) , 
	IN INVVAT SMALLINT , 
	IN INVHDRTXT VARCHAR(256) , 
	OUT SUCCESS SMALLINT ) 
	DYNAMIC RESULT SETS 1 
	LANGUAGE RPGLE 
	SPECIFIC WORKSHOP/CREATEINVOICEHEADER 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	EXTERNAL NAME 'WORKSHOP/IOINVOICE(CRTONEINVHDR)' 
	PARAMETER STYLE SQL ; 
  
GRANT ALTER , EXECUTE   
ON SPECIFIC PROCEDURE WORKSHOP/CREATEINVOICEHEADER 
TO MATHY ; 
  
GRANT ALTER , EXECUTE   
ON SPECIFIC PROCEDURE WORKSHOP/CREATEINVOICEHEADER 
TO PIETER ; 
  
GRANT ALTER , EXECUTE   
ON SPECIFIC PROCEDURE WORKSHOP/CREATEINVOICEHEADER 
TO PUBLIC ; 
  
GRANT ALTER , EXECUTE   
ON SPECIFIC PROCEDURE WORKSHOP/CREATEINVOICEHEADER 
TO WOUTER ;
