--  Generate SQL 
--  Version:                   	V7R2M0 140418 
--  Generated on:              	04/25/16 10:18:16 
--  Relational Database:       	BMADE 
--  Standards Option:          	DB2 for i 
drop PROCEDURE WORKSHOP.createAddress  ;
CREATE PROCEDURE WORKSHOP.createAddress ( 
	IN "ID" CHAR(15) , 
	IN REF CHAR(15) , 
	IN STREET CHAR(30) , 
	IN NUMBER CHAR(5) , 
	IN BOX CHAR(5) , 
	IN ZIP CHAR(15) , 
	IN CITY CHAR(20) , 
	IN COUNTRY CHAR(3) , 
	IN ATYPE CHAR(5) , 
	OUT SUCCESS SMALLINT ) 
	DYNAMIC RESULT SETS 1 
	LANGUAGE RPGLE 
	SPECIFIC WORKSHOP.CRTONEADDR 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	EXTERNAL NAME 'WORKSHOP/IOADDRESS(CRTONEADDR)' 
	PARAMETER STYLE SQL ; 
  
GRANT ALTER , EXECUTE   
ON SPECIFIC PROCEDURE  WORKSHOP.createAddress 
TO MATHY ; 
  
GRANT EXECUTE   
ON SPECIFIC PROCEDURE  WORKSHOP.createAddress
TO PUBLIC ; 
  

