--  Generate SQL 
--  Version:                   	V7R2M0 140418 
--  Generated on:              	04/25/16 09:52:52 
--  Relational Database:       	BMADE 
--  Standards Option:          	DB2 for i 
set schema workshop;
drop  PROCEDURE WORKSHOP.READALLCODEHEADERS ;
CREATE PROCEDURE WORKSHOP.READALLCODEHEADER ( 
	IN ID CHAR(15),
	IN Code CHAR(15) )
	DYNAMIC RESULT SETS 1 
	LANGUAGE RPGLE 
	SPECIFIC WORKSHOP.READALLCODEHEADER 
	DETERMINISTIC 
	READS SQL DATA 
	CALLED ON NULL INPUT 
	EXTERNAL NAME 'WORKSHOP/IOCODES(GETCODHEADLST)' 
	PARAMETER STYLE GENERAL WITH NULLS ; 
  
COMMENT ON SPECIFIC PROCEDURE WORKSHOP.READALLCODEHEADER 
	IS 'Reads all codes' ; 
  
GRANT ALTER , EXECUTE   
ON SPECIFIC PROCEDURE WORKSHOP.READALLCODEHEADER 
TO MATHY ; 
  
GRANT EXECUTE   
ON SPECIFIC PROCEDURE WORKSHOP.READALLCODEHEADER 
TO PUBLIC ;

