--  Generate SQL 
--  Version:                   	V7R2M0 140418 
--  Generated on:              	04/25/16 09:52:52 
--  Relational Database:       	BMADE 
--  Standards Option:          	DB2 for i 
set schema workshop;
drop  PROCEDURE WORKSHOP.READONECODEDETAIL ;
CREATE PROCEDURE WORKSHOP.READONECODEDETAIL ( 
	IN ID CHAR(15),
	IN Code CHAR(15) )
	DYNAMIC RESULT SETS 1 
	LANGUAGE RPGLE 
	SPECIFIC WORKSHOP.READONECODEDETAIL 
	DETERMINISTIC 
	READS SQL DATA 
	CALLED ON NULL INPUT 
	EXTERNAL NAME 'WORKSHOP/IOCODES(GETONECOD)' 
	PARAMETER STYLE GENERAL WITH NULLS ; 
  
COMMENT ON SPECIFIC PROCEDURE WORKSHOP.READONECODEDETAIL 
	IS 'Reads one code' ; 
  
GRANT ALTER , EXECUTE   
ON SPECIFIC PROCEDURE WORKSHOP.READONECODEDETAIL 
TO MATHY ; 
  
GRANT EXECUTE   
ON SPECIFIC PROCEDURE WORKSHOP.READONECODEDETAIL 
TO PUBLIC ;

set schema workshop;
select * from contact;

call workshop.READONECODEDETAIL('293');
