--  Generate SQL 
--  Version:                   	V7R2M0 140418 
--  Generated on:              	23/05/17 13:26:10 
--  Relational Database:       	TALENTIT 
--  Standards Option:          	DB2 for i 
CREATE PROCEDURE WORKSHOP/READALLCODEDETAIL ( 
	IN "ID" CHAR(3) ) 
	LANGUAGE RPGLE 
	SPECIFIC WORKSHOP/READALLCODEDETAIL 
	NOT DETERMINISTIC 
	READS SQL DATA 
	CALLED ON NULL INPUT 
	EXTERNAL NAME 'WORKSHOP/IOCODES(GETCODLSTID)' 
	PARAMETER STYLE GENERAL WITH NULLS ; 
  
GRANT ALTER , EXECUTE   
ON SPECIFIC PROCEDURE WORKSHOP/READALLCODEDETAIL 
TO MATHY ; 
  
GRANT ALTER , EXECUTE   
ON SPECIFIC PROCEDURE WORKSHOP/READALLCODEDETAIL 
TO PIETER ; 
  
GRANT EXECUTE   
ON SPECIFIC PROCEDURE WORKSHOP/READALLCODEDETAIL 
TO PUBLIC ; 
  
GRANT ALTER , EXECUTE   
ON SPECIFIC PROCEDURE WORKSHOP/READALLCODEDETAIL 
TO TSECOFR ;
