--  Generate SQL 
--  Version:                   	V7R2M0 140418 
--  Generated on:              	23/05/17 13:26:31 
--  Relational Database:       	TALENTIT 
--  Standards Option:          	DB2 for i 
CREATE PROCEDURE WORKSHOP/READALLCODEDETAILS ( 
	IN "ID" CHAR(3) , 
	IN LISTTYPE CHAR(1) , 
	IN COUNTREQ INTEGER , 
	IN COUNTRET INTEGER , 
	IN OUTPUTTYPE CHAR(1) , 
	OUT OUTCODES VARCHAR(256) ) 
	LANGUAGE RPGLE 
	SPECIFIC WORKSHOP/READALLCODEDETAILS 
	NOT DETERMINISTIC 
	READS SQL DATA 
	CALLED ON NULL INPUT 
	EXTERNAL NAME 'WORKSHOP/IOCODES(GETCODELIST)' 
	PARAMETER STYLE GENERAL WITH NULLS ; 
  
GRANT ALTER , EXECUTE   
ON SPECIFIC PROCEDURE WORKSHOP/READALLCODEDETAILS 
TO MATHY ; 
  
GRANT ALTER , EXECUTE   
ON SPECIFIC PROCEDURE WORKSHOP/READALLCODEDETAILS 
TO PIETER ; 
  
GRANT EXECUTE   
ON SPECIFIC PROCEDURE WORKSHOP/READALLCODEDETAILS 
TO PUBLIC ; 
  
GRANT ALTER , EXECUTE   
ON SPECIFIC PROCEDURE WORKSHOP/READALLCODEDETAILS 
TO TSECOFR ;
