--  Generate SQL 
--  Version:                   	V7R2M0 140418 
--  Generated on:              	04/21/16 17:05:56 
--  Relational Database:       	BMADE 
--  Standards Option:          	DB2 for i 

set schema workshop;
select * from price;

CREATE PROCEDURE WORKSHOP.READPRODUCTPRICEFROMDATE ( 
	IN IDPROD CHAR(15) , 
	IN IDATE DATE ) 
	DYNAMIC RESULT SETS 1 
	LANGUAGE RPGLE 
	SPECIFIC WORKSHOP.READPRODUCTPRICEFROMDATE 
	DETERMINISTIC 
	READS SQL DATA 
	CALLED ON NULL INPUT 
	EXTERNAL NAME 'WORKSHOP/IOPRICES(GETALLPRIBYDAT)' 
	PARAMETER STYLE SQL ; 
  
COMMENT ON SPECIFIC PROCEDURE WORKSHOP.READPRODUCTPRICEFROMDATE 
	IS 'Reads all the product prices for a product from a date' ; 
  
GRANT ALTER , EXECUTE   
ON SPECIFIC PROCEDURE WORKSHOP.READPRODUCTPRICEFROMDATE 
TO MATHY ; 
  
GRANT EXECUTE   
ON SPECIFIC PROCEDURE WORKSHOP.READPRODUCTPRICEFROMDATE 
TO PUBLIC ;


call WORKSHOP.READPRODUCTPRICEFROMDATE ('1002', '2012-01-01');