--  Generate SQL 
--  Version:                   	V7R2M0 140418 
--  Generated on:              	04/22/16 15:46:57 
--  Relational Database:       	BMADE 
--  Standards Option:          	DB2 for i 
drop PROCEDURE WORKSHOP.UPDATECUSTOMER;
CREATE PROCEDURE WORKSHOP.UPDATECUSTOMER ( 
	IN "ID" varchar(15) , 
	IN NAME varchar(50) , 
	IN CUSVAT varchar(15) , 
	IN PHONE varchar(20) , 
	IN MOBILE varchar(20) , 
	IN FAX varchar(20) , 
	IN EMAIL varchar(30) , 
	IN WEBSITE varchar(40) , 
	IN "TYPE" varchar(5) , 
	IN CLASS varchar(5) , 
	IN LANG varchar(5) , 
	IN CUR varchar(5) , 
	IN PAY varchar(5) , 
	IN ACT varchar(100) , 
	IN ACCNT varchar(20) , 
	IN INFO varchar(50) , 
	OUT SUCCESS SMALLINT ) 
	LANGUAGE RPGLE 
	SPECIFIC WORKSHOP.UPDATECUSTOMER 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	EXTERNAL NAME 'WORKSHOP/IOCUSTOMER(UPDONECUST)' 
	PARAMETER STYLE SQL ; 
  
GRANT ALTER , EXECUTE   
ON SPECIFIC PROCEDURE WORKSHOP.UPDATECUSTOMER 
TO MATHY ; 
  
GRANT EXECUTE   
ON SPECIFIC PROCEDURE WORKSHOP.UPDATECUSTOMER 
TO PUBLIC ; 
  
GRANT ALTER , EXECUTE   
ON SPECIFIC PROCEDURE WORKSHOP.UPDATECUSTOMER 
TO QDFTOWN ;
