--  Generate SQL 
--  Version:                   	V7R2M0 140418 
--  Generated on:              	24/05/17 15:57:24 
--  Relational Database:       	TALENTIT 
--  Standards Option:          	DB2 for i 
CREATE PROCEDURE WORKSHOP/UPDATECUSTOMER ( 
	IN "ID" CHAR(15) , 
	IN NAME CHAR(50) , 
	IN CUSVAT CHAR(15) , 
	IN PHONE CHAR(20) , 
	IN MOBILE CHAR(20) , 
	IN FAX CHAR(20) , 
	IN EMAIL CHAR(30) , 
	IN WEBSITE CHAR(40) , 
	IN "TYPE" CHAR(5) , 
	IN CLASS CHAR(5) , 
	IN LANG CHAR(5) , 
	IN CUR CHAR(5) , 
	IN PAY CHAR(5) , 
	IN ACT CHAR(100) , 
	IN ACCNT CHAR(20) , 
	IN INFO CHAR(50) , 
	OUT SUCCESS SMALLINT ) 
	LANGUAGE RPGLE 
	SPECIFIC WORKSHOP/UPDATECUSTOMER 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	EXTERNAL NAME 'WORKSHOP/IOCUSTOMER(UPDONECUST)' 
	PARAMETER STYLE SQL ; 
  
GRANT ALTER , EXECUTE   
ON SPECIFIC PROCEDURE WORKSHOP/UPDATECUSTOMER 
TO JELTE ; 
  
GRANT ALTER , EXECUTE   
ON SPECIFIC PROCEDURE WORKSHOP/UPDATECUSTOMER 
TO MATHY ; 
  
GRANT ALTER , EXECUTE   
ON SPECIFIC PROCEDURE WORKSHOP/UPDATECUSTOMER 
TO PIETER ; 
  
GRANT ALTER , EXECUTE   
ON SPECIFIC PROCEDURE WORKSHOP/UPDATECUSTOMER 
TO PUBLIC ; 
  
GRANT ALTER , EXECUTE   
ON SPECIFIC PROCEDURE WORKSHOP/UPDATECUSTOMER 
TO TSECOFR ;
