--  Generate SQL 
--  Version:                   	V7R2M0 140418 
--  Generated on:              	23/05/17 13:36:33 
--  Relational Database:       	TALENTIT 
--  Standards Option:          	DB2 for i 
CREATE PROCEDURE WORKSHOP/UPDATEADDRESS ( 
	IN PID CHAR(15) , 
	IN REF CHAR(15) , 
	IN STREET CHAR(30) , 
	IN NUMBER CHAR(5) , 
	IN BOX CHAR(5) , 
	IN ZIP CHAR(15) , 
	IN CITY CHAR(20) , 
	IN COUNTRY CHAR(3) , 
	IN "TYPE" CHAR(5) , 
	OUT SUCCESS SMALLINT ) 
	DYNAMIC RESULT SETS 1 
	LANGUAGE RPGLE 
	SPECIFIC WORKSHOP/UPDATEADDRESS 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	EXTERNAL NAME 'WORKSHOP/IOADDRESS(UPDONEADDR)' 
	PARAMETER STYLE SQL ; 
  
GRANT ALTER , EXECUTE   
ON SPECIFIC PROCEDURE WORKSHOP/UPDATEADDRESS 
TO JENTE ; 
  
GRANT ALTER , EXECUTE   
ON SPECIFIC PROCEDURE WORKSHOP/UPDATEADDRESS 
TO MATHY ; 
  
GRANT ALTER , EXECUTE   
ON SPECIFIC PROCEDURE WORKSHOP/UPDATEADDRESS 
TO PIETER ; 
  
GRANT ALTER , EXECUTE   
ON SPECIFIC PROCEDURE WORKSHOP/UPDATEADDRESS 
TO PUBLIC ; 
  
GRANT ALTER , EXECUTE   
ON SPECIFIC PROCEDURE WORKSHOP/UPDATEADDRESS 
TO WITO ;
