--  Generate SQL 
--  Version:                   	V7R2M0 140418 
--  Generated on:              	24/05/17 15:57:52 
--  Relational Database:       	TALENTIT 
--  Standards Option:          	DB2 for i 
CREATE PROCEDURE WORKSHOP/UPDATEINVOICEHEADER ( 
	IN CHAR(15) , 
	IN CUSID CHAR(15) , 
	IN ADDID CHAR(15) , 
	IN ADDDLVID CHAR(15) , 
	IN CRTDATE DATE , 
	IN CRTUSR CHAR(15) , 
	IN UPDDATE DATE , 
	IN UPDUSR CHAR(15) , 
	IN INVDATE DATE , 
	IN DUEDATE DATE , 
	IN STATUS CHAR(5) , 
	IN "TYPE" CHAR(5) , 
	IN INVVAT SMALLINT , 
	IN HTEXT CHAR(256) , 
	OUT SUCCESS SMALLINT ) 
	DYNAMIC RESULT SETS 1 
	LANGUAGE RPGLE 
	SPECIFIC WORKSHOP/UPDATEINVOICEHEADER 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	EXTERNAL NAME 'WORKSHOP/IOINVOICE(UPDONEINVHDR)' 
	PARAMETER STYLE SQL ; 
  
GRANT ALTER , EXECUTE   
ON SPECIFIC PROCEDURE WORKSHOP/UPDATEINVOICEHEADER 
TO JELTE ; 
  
GRANT ALTER , EXECUTE   
ON SPECIFIC PROCEDURE WORKSHOP/UPDATEINVOICEHEADER 
TO MATHY ; 
  
GRANT ALTER , EXECUTE   
ON SPECIFIC PROCEDURE WORKSHOP/UPDATEINVOICEHEADER 
TO PIETER ; 
  
GRANT ALTER , EXECUTE   
ON SPECIFIC PROCEDURE WORKSHOP/UPDATEINVOICEHEADER 
TO PUBLIC ; 
  
GRANT ALTER , EXECUTE   
ON SPECIFIC PROCEDURE WORKSHOP/UPDATEINVOICEHEADER 
TO WOUTER ;
